### ISSUE TITLE
Asset on loading model

### ISSUE THREAD

**Issue by abigos** [Unity-Technologies/barracuda-release#191]
Hi,

I get an assert when I attempt to load the enclosed model - it's not clear what the problem is, do I need to do some more input channel shuffling?   I'm trying to take a very simple model and duplicate it multiple times (16 in this case, but typically would be larger) whilst sharing all the constants, each batch would then execute this in parallel.  I'd appreciate if you could confirm this is a reasonable approach to speedup execution of a small model.

Thanks

[tile_1x16.zip](https://github.com/Unity-Technologies/barracuda-release/files/6639191/tile_1x16.zip)

Log from 1.4 but I see the same for 2.1 preview.
`Asset import failed, "Assets/Models/tile_1x16.onnx" > AssertionException: Assertion failure. Values are not equal.
Expected: 2 == 1
InferOutputRank.Dense inputRanks
UnityEngine.Assertions.Assert.Fail (System.String message, System.String userMessage) (at <4577339eb6f24e22b2a4431e652bd511>:0)
UnityEngine.Assertions.Assert.AreEqual[T] (T expected, T actual, System.String message, System.Collections.Generic.IEqualityComparer1[T] comparer) (at <4577339eb6f24e22b2a4431e652bd511>:0)
UnityEngine.Assertions.Assert.AreEqual[T] (T expected, T actual, System.String message) (at <4577339eb6f24e22b2a4431e652bd511>:0)
UnityEngine.Assertions.Assert.AreEqual (System.Int32 expected, System.Int32 actual, System.String message) (at <4577339eb6f24e22b2a4431e652bd511>:0)
Unity.Barracuda.Compiler.IRShapeInferenceHelper.RankInference.InferOutputRank (Unity.Barracuda.Layer layer, System.Int32[] inputRanks) (at Library/PackageCache/com.unity.barracuda@1.4.0-preview/Barracuda/Runtime/Core/Compiler/ShapeInference/IRRankInferenceHelper.cs:21)
Unity.Barracuda.Compiler.IRShapeInferenceHelper.RankInference.UpdateKnownTensorRanks (Unity.Barracuda.Model model, System.Collections.Generic.IDictionary2[TKey,TValue] ranksByName) (at Library/PackageCache/com.unity.barracuda@1.4.0-preview/Barracuda/Runtime/Core/Compiler/ShapeInference/IRRankInferenceHelper.cs:256)
Unity.Barracuda.Compiler.Passes.IRShapeInferenceAndConstantFusing.FuseShapesIntoConstants (Unity.Barracuda.Model& model, System.Collections.Generic.IDictionary2[TKey,TValue] shapesByName, System.Collections.Generic.IDictionary2[TKey,TValue] ranksByName) (at Library/PackageCache/com.unity.barracuda@1.4.0-preview/Barracuda/Runtime/Core/Compiler/Passes/IRShapeInferenceAndConstantFusing.cs:65)
Unity.Barracuda.Compiler.Passes.IRShapeInferenceAndConstantFusing.Run (Unity.Barracuda.Model& model) (at Library/PackageCache/com.unity.barracuda@1.4.0-preview/Barracuda/Runtime/Core/Compiler/Passes/IRShapeInferenceAndConstantFusing.cs:23)
Unity.Barracuda.Compiler.Passes.ValidateNCHWShapesPass.Run (Unity.Barracuda.Model model, System.Collections.Generic.List1[Unity.Barracuda.Model+ImporterWarning]& warnings) (at Library/PackageCache/com.unity.barracuda@1.4.0-preview/Barracuda/Runtime/Core/Compiler/Passes/ValidatePasses.cs:52)
Unity.Barracuda.Compiler.Passes.ValidateNCHWPass.Run (Unity.Barracuda.Model model, System.Collections.Generic.List1[Unity.Barracuda.Model+ImporterWarning]& warnings) (at Library/PackageCache/com.unity.barracuda@1.4.0-preview/Barracuda/Runtime/Core/Compiler/Passes/ValidatePasses.cs:211)
Unity.Barracuda.Compiler.Passes.IntermediateToRunnableNHWCPass.Run (Unity.Barracuda.Model& model) (at Library/PackageCache/com.unity.barracuda@1.4.0-preview/Barracuda/Runtime/Core/Compiler/Passes/IntermediateToRunnableNHWCPass.cs:29)
Unity.Barracuda.ONNX.ONNXModelConverter.Convert (Google.Protobuf.CodedInputStream inputStream) (at Library/PackageCache/com.unity.barracuda@1.4.0-preview/Barracuda/Runtime/ONNX/ONNXModelConverter.cs:170)
Unity.Barracuda.ONNX.ONNXModelConverter.Convert (System.String filePath) (at Library/PackageCache/com.unity.barracuda@1.4.0-preview/Barracuda/Runtime/ONNX/ONNXModelConverter.cs:83)
Unity.Barracuda.ONNXModelImporter.OnImportAsset (UnityEditor.Experimental.AssetImporters.AssetImportContext ctx) (at Library/PackageCache/com.unity.barracuda@1.4.0-preview/Barracuda/Editor/ONNXModelImporter.cs:58)
UnityEditor.Experimental.AssetImporters.ScriptedImporter.GenerateAssetData (UnityEditor.Experimental.AssetImporters.AssetImportContext ctx) (at <2b3dc6c508754760a989e810beb820a9>:0)`

**Comment by FlorentGuinier** [comment]
Hi @abigos 

In regard to the error: This model is actually not valid in regar to ONNX specification! ONNX Gemm is expecting a rank 2 inputs however here we have: 
![image](https://user-images.githubusercontent.com/20201082/121872812-0312e580-cd06-11eb-9619-4239e7f6ac01.png)

1 = rank 2
2 = rank 1 
3 = expect rank 2 -->error.

I have however relaxed the importer assert around that as it seems pytorch do this a lot and we actually support this behavior in term of inference. TLDR you can wait for next release or add a reshape between the gather and the Gemm.

In regard to speed:
* On GPU this won't probably help much as we shedule all operator separately so you will rely on the driver efficiency and overlapping independant dispatch here, this will probably work ok ish on some hardware and less on some others, in general i expect the gain to be not huge if any, also because bigger workload per dispatch is often better to get good GPU occupancy and even to write better implementation (even if we mainly optimize for batch == 1 in the case of Barracuda).
* On CPU Burst backend this might work as all operators will actually get there own jobs and be scheduled on there own, helping in jobs granularity. However our implementation are in general threaded and going wide when they can, so i would profile there, might be the same in the end!

Recap: Imho GPU no gain or worst, CPU could be great. In both case i would definitively profile!

Hope it helps! I'm closing the case, however feel free to reopen to discuss more!
Florent
