### ISSUE TITLE
Incorrect reshape operation for dynamic batch size, "ArgumentException: Off-axis dimensions must match" if using static batch sizes - same model architecture

### ISSUE THREAD

**Issue by carlsc2** [Unity-Technologies/barracuda-release#210]
Hello, I have an onnx model that I'm trying to run; I'm using the barracuda 2.1.0 release. The model runs with an input size of 1, but I need larger batches for performance reasons, which is where it falls apart.

In summary, I have 2 main issues:
 - If I create an onnx model with dynamic input size, I immediately get "ArgumentException: Cannot reshape array of size 1806336 into shape (n:1, h:1, w:96, c:96)" - the shape is wrong here, it should be running with a batch of size 196
- If I use fixed input size, the model gets halfway through execution before failing with "ArgumentException: Off-axis dimensions must match". This might be the same issue as #201.

I'm restricted to opset version 11 because of dynamic sizes with the Pad operator (pytorch) so I was wondering if opset 9 would be better supported, but after tweaking my architecture (so that I could export with opset 9) I still ran into issue 2. I've tried numerous tweaks over the past week but everything basically results in one of the two aforementioned issues.

My exported onnx model runs fine with python / onnxruntime; it seems that the issues are specifically with Unity. Any help is appreciated.

P.S. I already reached out via email since that was the resolution to #201, but am creating this issue to keep track of things as per @amirebrahimi.

P.P.S Ideally I'd like to resolve the first issue, but am fine with just the second.

**Comment by amirebrahimi** [comment]
Hi @carlsc2.

So, there are a few things going on here. As you mentioned, using a fixed input size fixes #1 and at the moment we don't have a quick fix for that as it involves re-calculating shapes at run-time. However, this is a feature we hope to add in a future release.

Re: #2, this was due to an improper transformation for broadcasting purposes at `Add_46`. I've fixed that and will send you a patch that you can apply for now.

One thing to note is that this model currently has many warnings on import for the Resize nodes. You have two attributes (i.e. `nearest_mode` and `coordinate_transformation_mode`) that we don't support fully. So, keep that in mind if you are comparing to onnx or another runtime.
