### ISSUE TITLE
WebGL Build - Kernel TextureToTensor and TextureToTensor_NHWC are both missing

### ISSUE THREAD

**Issue by LuanaPorciuncula** [Unity-Technologies/barracuda-release#227]
Hi!
I'm working on a unity project that performs pose estimation in Unity with the Barracuda inference library (2.1.0-preview).
I followed this tutorial https://github.com/cj-mills/Barracuda-PoseNet-Tutorial, and attempted to build to WebGL.
In the Unity Editor, the project runs correctly. But unfortunately, I'm getting this error with the WebGL development build: Kernel TextureToTensor and TextureToTensor_NHWC are both missing.
I've tried using WorkerFactory.Type.CSharp and WorkerFactory.Type.CSharpBurst, but I still get the same error.
Any idea why that might be happening or how to fix it?

**Comment by AlexRibard** [comment]
Hello @LuanaPorciuncula,
This issue is two fold:
- WebGL does not support compute shaders.
- Our implementation of `ToRenderTexture` unfortunately makes a call to a compute shader dispatch. So you will be getting an issue like that if you ever try to call `ToRenderTexture` on a WebGL build.

We have a few solutions that will come out in a upcoming Barracuda release to fix this issue.
Unfortunately as of today, the only workaround is that you need to create a texture from the Tensor data yourself.

Here is a good example of how to fill a texture on the CPU
https://github.com/Unity-Technologies/UnityTextureAccessApiExamples

Let me know if you need additional help

**Comment by AlexRibard** [comment]
closing for now, feel free to comment on the thread if you need additional help
