### ISSUE TITLE
ModelLoader.Load(...) blocks the CPU

### ISSUE THREAD

**Issue by edgar-rodrigo-santos** [Unity-Technologies/barracuda-release#235]
Hi,

I'm noticing that ModelLoader.Load(bytes) is synchrounous and blocks the CPU until it's done. 
A ~6.6Mb onnx model takes between 350-700ms to load on Hololens2, which would be ok if the CPU was not blocked during that time.

We tried running it in a separate thread but it doesn't work because you're using NativeArrays which can only be used in the main thread.

We also tried using the Job System but it is not possible to return a reference type (in this case "Model") from a Job.

Is there a way around it? If not, do you plan on optimizing the ModelLoader.Load method to work over several frames (and/or use the Job System, and/or other relevant techniques?)

Thank you

**Comment by FlorentGuinier** [comment]
Hi edgar-rodrigo-santos,

Thanks for this great feedback, we will look into this and get back to you. In the meantime could you explain your use case and project deadline to scope this please?

Thanks
Florent

**Comment by FlorentGuinier** [comment]
As alexandrk stated it seems the related compute shader could not be compiled, likely because target platform does not allow compute shader. You can validate this by looking at https://docs.unity3d.com/ScriptReference/SystemInfo-supportsComputeShaders.html (or at compile kernel aka *.cs in inspector). FYI we currently have a WIP pixel shader worker in barracuda 2.3.1 (support tensor of rank 4 or less + not all operator yet supported) witch might help if compute shader are not supported but GPU is along pixel shader. If the VM do note have access to gpu then the best bet Burst backend however for heavy load such as convolution on images it is probably be an order of magnitude slower than a GPU (witch typically have at least an order of magnitude more FLOPS than same gen CPU hence the difference).

**Comment by edgar-rodrigo-santos** [comment]
The use case is realtime analysis of the device camera frames. 
This issue is already affecting us and we fleshed it now because we are currently in the process of improving our current solution as much as possible, so I would say sooner rather than later.

Thank you for your support.

**Comment by amirebrahimi** [comment]
@edgar-rodrigo-santos - how often are you loading onnx models? Can this load happen at launch? Also, just to confirm -- are just talking about loading an already converted ONNX file since you are using `ModelLoader.Load(bytes)`. Is this an asset that is coming through Resources.Load, an asset bundle, or an Addressable?

**Comment by amirebrahimi** [comment]
I may be able to introduce a coroutine-based async loader with relative ease, but would you kindly send an example model to us at barracuda-support at unity3d dot com, so that I can make sure that it maintains real-time performance on any given frame?

**Comment by edgar-rodrigo-santos** [comment]
We are receiving the onnx file bytes over the network (no Resources.Load or asset bundle or addressables).
Our app relies on the concept of dynamic content, so the loading can't happen on launch but on a "loading phase" in which we need to give visual feedback to the user (thus we can't block the cpu).

Unfortunately, I can't send you this specific model.

A coroutine-based async loader sounds like exactly what we'd need.

**Comment by amirebrahimi** [comment]
The coroutine-based async loaders have landed to our main branch. Look for it in the next release.
