### ISSUE TITLE
Installing Barracuda 2.3.1-preview fails to locate Google.Protobuf.dll

### ISSUE THREAD

**Issue by pasmai** [Unity-Technologies/barracuda-release#237]
I am using Unity **2020.3.22f1**
I added **Barracuda 2.3.1-preview** through the package manager.

And I get the following error:
`error CS0006: Metadata file 'C:/Users/username/Documents/object-classification/Source/Unity/Object Detection/Library/PackageCache/com.unity.barracuda@2.0.0/Barracuda/Runtime/Plugins/ProtoBuffer/Google.Protobuf.dll' could not be found`

It is looking for the Protobuf.dll file in the path barracuda@**2.0.0** which does not exist. It should be com.unity.barracuda@**2.3.1-preview**/Barracuda/Runtime/Plugins/ProtoBuffer/Google.Protobuf.dll.

Is this a problem with barracuda or Unity? Are there any steps to fix it?

**Comment by FlorentGuinier** [comment]
Hi pasmai,

This is not an error we are aware of (I just tried a fresh import of Barracuda 2.3.1-preview in fresh project under Unity 2020.3 and could not repro). 

Could you try to reimport project / delete library folder? My guess would be that this problem is triggered by a faulty project library dependancy cache.

Florent

**Comment by pasmai** [comment]
Creating a new project worked. But only on the second try, for some reason. :/
Not sure why it is acting so weird. 

Thank you for taking the time to try it out.
