### ISSUE TITLE
Asset import failed, "Assets/gpt2.onnx" > AssertionException: Assertion failure. Value was False

### ISSUE THREAD

**Issue by githubuserlan** [Unity-Technologies/barracuda-release#249]
Hello, I want to load my pretrained GPT2 model into unity. Currently it produces a line of text as output, however, unity doesn´t seem to like my ONNX file. This is the error message I get: 

Asset import failed, "Assets/gpt2.onnx" > AssertionException: Assertion failure. Value was False
Expected: True
UnityEngine.Assertions.Assert.Fail (System.String message, System.String userMessage) (at <0ee480759f3d481d82ada245dc74f9fd>:0)
UnityEngine.Assertions.Assert.IsTrue (System.Boolean condition, System.String message) (at <0ee480759f3d481d82ada245dc74f9fd>:0)
UnityEngine.Assertions.Assert.IsTrue (System.Boolean condition) (at <0ee480759f3d481d82ada245dc74f9fd>:0)
Unity.Barracuda.Compiler.Passes.Cleanup.RemoveNoOpsPass.Run (Unity.Barracuda.Model& model) (at Library/PackageCache/com.unity.barracuda@2.4.0-preview/Barracuda/Runtime/Core/Compiler/Passes/RemoveNoOpsPass.cs:50)
Unity.Barracuda.Compiler.Passes.IntermediateToRunnableNHWCPass.Run (Unity.Barracuda.Model& model) (at Library/PackageCache/com.unity.barracuda@2.4.0-preview/Barracuda/Runtime/Core/Compiler/Passes/IntermediateToRunnableNHWCPass.cs:29)
Unity.Barracuda.ONNX.ONNXModelConverter.Convert (Google.Protobuf.CodedInputStream inputStream) (at Library/PackageCache/com.unity.barracuda@2.4.0-preview/Barracuda/Runtime/ONNX/ONNXModelConverter.cs:188)
Unity.Barracuda.ONNX.ONNXModelConverter.Convert (System.String filePath) (at Library/PackageCache/com.unity.barracuda@2.4.0-preview/Barracuda/Runtime/ONNX/ONNXModelConverter.cs:98)
Unity.Barracuda.ONNXModelImporter.OnImportAsset (UnityEditor.AssetImporters.AssetImportContext ctx) (at Library/PackageCache/com.unity.barracuda@2.4.0-preview/Barracuda/Editor/ONNXModelImporter.cs:65)
UnityEditor.AssetImporters.ScriptedImporter.GenerateAssetData (UnityEditor.AssetImporters.AssetImportContext ctx) (at <7ac35247888b44f4a7e290f1f6bb33f3>:0)
UnityEditorInternal.InternalEditorUtility:ProjectWindowDrag(HierarchyProperty, Boolean)
UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr, Boolean&)

UnityEngine.GUIUtility:ProcessEvent (int,intptr,bool&)

Here is a link to the Onnx file: https://drive.google.com/file/d/19S7Toi09U47MIMTtF1KY2oNZORWp830N/view?usp=sharing
I´m working with unity version 2020.3.25f1 and Barracuda 2.4.0-preview.
Thanks for any help!

**Comment by AlexRibard** [comment]
Hi! Thanks for sharing the model, it is quite useful.
Actually we have a incorrect check in our importer. The fix is quite simple
![image](https://user-images.githubusercontent.com/12990800/148818279-f2d19ee8-ebcc-469b-a05e-b59e2ed97706.png)
In `RemoveNoOpsPass.cs`

I am not quite sure of the input shapes of the model, so I cannot directly check if inference is valid.
Is your example from https://github.com/onnx/models/tree/master/text/machine_comprehension/gpt-2 ?
Or can you share with me the shapes of the input typically encountered
```
    batch_size = ?
    seq_len = ?
    total_seq_len = ?
    past_seq_len = ?
```

Let me know

**Comment by githubuserlan** [comment]
Hi, sorry for the late reply! I used this https://github.com/pranavpsv/Genre-Based-Story-Generator as the basis. I just changed the training files.

**Comment by AlexRibard** [comment]
Hello, the problem lies in our importer.
We are working on making the import process less error prone.
It should address issues like this.
Might take some time to land, so I'd advise to change model.
Let us know if that is not an option and this is greatly impacting your project.
If this is the case, you can contact us via email at barracuda-support@unity3d.com

**Comment by FlorentGuinier** [comment]
Closing the issue as the problem as been explained and solution is being worked on in our internal roadmap.
