### ISSUE TITLE
Performance of LSTM-based networks

### ISSUE THREAD

**Issue by tvkamara** [Unity-Technologies/barracuda-release#255]
Hello. I'm currently benchmarking an LSTM-based network on Barracuda and getting around 60 fps with WorkerFactory.Type.CSharpBurst but only around 20 fps with WorkerFactory.Type.ComputePrecompiled. I'm creating the input simply with:

int[] shape = new int[] { 1, 6, 20 };
Tensor input = new Tensor(shape);

I'm wondering what would be the most efficient way of inputting data to a model which is run on the GPU if one is not using textures as input? In PyTorch, I can run the same inference in 2 ms.

**Comment by FlorentGuinier** [comment]
Hi @tvkamara 

As you hint you are probably bound because of the blocking data exchange between GPU and CPU here. `WorkerFactory.Type.ComputePrecompiled` will most likely be faster than `Burst` (still depend on the hardware) if the data can remain on the GPU all the time. However if you need to upload or download the data on a frame by frame basis for CPU access Burst is most likely to be the best option. 

To create your input using GPU data but not texture you can use : 
`public Tensor(int n, int h, int w, int c, ComputeBuffer srcBuffer, string name = "")`
Also to get the data back on CPU without actively syncing CPU and GPU you can use 
`Tensor.PrepareCacheForAccess(bool blocking = FALSE) witch will return true when the data is ready (most likely +/-3 frames after inference is done).`

Hope it helps,
Florent

**Comment by FlorentGuinier** [comment]
I'm closing the question as i feel it was answered, please reopen if needed.

**Comment by tvkamara** [comment]
Hi, thanks for the answer. Even after using

`srcBuffer = new ComputeBuffer(120, 4);
input = new Tensor(1, 1, 6, 20, srcBuffer, "fakeInput");`

in Start() and only doing:

`m_Worker.Execute(input);`

in Update(), I only get around 20fps using ComputePrecompiled. I guess the LSTM layers (which I have 8) are just too compute heavy? It is a bit weird that it is so fast in PyTorch though. Attached some screenshots from Profiler and my model.

![LSTM_precompiled_2](https://user-images.githubusercontent.com/8319136/150931003-f30c35fa-752f-4aec-9478-280977ddeeca.png)
![LSTM_precompiled](https://user-images.githubusercontent.com/8319136/150931006-45accdd5-82a3-47b8-8517-ff9f11c25557.png)
[model.zip](https://github.com/Unity-Technologies/barracuda-release/files/7931475/model.zip)

**Comment by FlorentGuinier** [comment]
Hi @tvkamara 
Thanks for the profiler screenshot! I just realized now that the model is LSTM based! So there are a bunch of problem there:
* We only support LSTM for the ML-Agent use case https://github.com/Unity-Technologies/ml-agents
* At the moment we don't provide a GPU based implementation of the LSTM.

So you are in uncharted territory here. Any chance you could use a model without LSTM or go via ML-Agent?

**Comment by tvkamara** [comment]
Thanks for the quick response! That actually explains a lot. I'm in quite early stage of things, I currently just wanted to quickly show that the model we use in PyTorch could be used inside a game engine. And with the CPU implementation it at least runs in "real-time". I will look into ml-agents, not that familiar with them.

Alternatively I will just keep my eyes open for a GPU-based implementation :). There seemed to be a lot of issues mentioning the use of LSTMs in issues so it would be a welcome addon.
