### ISSUE TITLE
NotSupportedException: Format version not supported: 242

### ISSUE THREAD

**Issue by chinmaychinara91** [Unity-Technologies/barracuda-release#267]
I am using barracuda 2.0 in Unity 2021.2.12f1.

I try to load a model during runtime using:
`model = ModelLoader.Load(modelFilePath, verbose: true, skipWeights: false);`
where modelFilePath is a path which can be "outside" of the assets folder (a major requirement for my goal)

The error:

> NotSupportedException: Format version not supported: 242
> Unity.Barracuda.ModelLoader.Load (System.IO.BinaryReader fileReader, System.Boolean verbose, System.Boolean applyPatching, System.Boolean skipWeights) (at Library/PackageCache/com.unity.barracuda@2.0.0/Barracuda/Runtime/Core/ModelLoader.cs:111)
> Unity.Barracuda.ModelLoader.Load (System.String filepath, System.Boolean verbose, System.Boolean skipWeights) (at Library/PackageCache/com.unity.barracuda@2.0.0/Barracuda/Runtime/Core/ModelLoader.cs:55)

Kindly assist.

**Comment by FlorentGuinier** [comment]
i would advice to look in that thread witch seems similar https://github.com/Unity-Technologies/barracuda-release/issues/254

**Comment by chinmaychinara91** [comment]
As per the solution at the end of the thread, it still assumes that we have the model file saved somewhere under assets (using AssetDatabase.LoadAssetPath) but my requirement is loading at runtime from any given location be it inside or outside.

I tried doing the UnityWebRequest approach of loading .onnx from any given path passed as the url below:

```c#
public IEnumerator LoadModelUrl(string url)
    {
        using UnityWebRequest www = UnityWebRequest.Get(url);
        {
            yield return www.SendWebRequest();
            if (www.error == null)
            {
                var loadedModel = ScriptableObject.CreateInstance<NNModel>();
                loadedModel.modelData = ScriptableObject.CreateInstance<NNModelData>();
                loadedModel.modelData.Value = www.downloadHandler.data;
            }
        }
    }
```

but it still gives me the same error.

**Comment by FlorentGuinier** [comment]
Seems to be that what you are looking for is:
[ONNXModelConverter::Convert()](https://github.com/Unity-Technologies/barracuda-release/blob/b1eac6c34b12b1ef5506fb7121a29eda2997efd1/Barracuda/Runtime/ONNX/ONNXModelConverter.cs#L94
)

The error being probably due to an ONNX file/byte array being directly mapped to loadedModel.modelData.Value. While we expected a byte array from a serialized Model.

Maybe to be more clear:
ONNX_file <-- The definition of a NN in the ONNX format (using protobuff). Barracuda can't run inference on it.
Model <-- The definition of a NN in the Barracuda format. Barracuda CAN run inference on it.
NNModel <-- A serializable version of the Barracuda model. Barracuda can't run inference on it. 

To go from ONNX_file to Model: 
* [ONNXModelConverter::Convert()](https://github.com/Unity-Technologies/barracuda-release/blob/b1eac6c34b12b1ef5506fb7121a29eda2997efd1/Barracuda/Runtime/ONNX/ONNXModelConverter.cs#L94
)
* or drop ONNX file in editor (ie the import process will do the convertion).
* or [AssetDatabase.LoadAssetAtPath()](https://docs.unity3d.com/ScriptReference/AssetDatabase.LoadAssetAtPath.html) (onnx file asset need to be in project).

To go from Model to NNModel
[ModelWriter::Save()](https://github.com/Unity-Technologies/barracuda-release/blob/b1eac6c34b12b1ef5506fb7121a29eda2997efd1/Barracuda/Runtime/Core/ModelWriter.cs#L37:28) via MMModelData.value see example [here](https://github.com/Unity-Technologies/barracuda-release/blob/b1eac6c34b12b1ef5506fb7121a29eda2997efd1/Barracuda/Editor/ONNXModelImporter.cs#L74)

To go from MMModel to Model
[ModelLoader::Load()](https://github.com/Unity-Technologies/barracuda-release/blob/b1eac6c34b12b1ef5506fb7121a29eda2997efd1/Barracuda/Runtime/Core/ModelLoader.cs#L101)

**Comment by chinmaychinara91** [comment]
Thanks ONNXModelConverter::Convert() did the trick.
