### ISSUE TITLE
After upgrading to 0.7, tensor.data.download fails.

### ISSUE THREAD

**Issue by guoguoguilai** [Unity-Technologies/barracuda-release#36]
It used to be "tensor.data.download(int)". How to fetch and convert data from tensor to float[] in 0.7?

**Comment by FlorentGuinier** [comment]
Hey guoguoguilai, 

This interface have changed to take the tensor shape rather than length as an argument. Thus you can use: "tensor.data.download(tensorShape)" instead.

BTW A simpler way to grab the data as float[] is `Tensor.readonlyArray` property.

Hope this help! Please reopen if this is not the answer you were looking for :)
