### ISSUE TITLE
Some questions and error :)

### ISSUE THREAD

**Issue by DanielDorDev** [Unity-Technologies/barracuda-release#55]
First of all thank you for the update!
I started using barracuda when it was version0.4 for my university project, and it helped me so much , i see so much potential :)
I am so happy with the new features, dilation, async cpu (with burst!) this is amazing! thank you!! 🥇 

When i try the new burst worker it fails when i try to execute( i use burst 1.3.0)

UnityException: ScheduleBatchedJobsAndComplete can only be called from the main thread.
Constructors and field initializers will be executed from the loading thread when loading a scene.
Don't use this function in the constructor or field initializers, instead move initialization code to the Awake or Start function.

Some question:

1) I use mobilenet, resnet50, and there i need to modify the pixels, cpu op is heavy (and not scalable to different preprocessing) is there a better way? Lets say adding a prelayer?  compute shaders?

2) About postprocessing, i want to apply sigmoid on the tensor output, i tried adding layer, but because the outputs length = 4,  it fails, what is the correct way doing that? more over peekoutput takes too much time, is it beacause i pass 1000 length? 

3)  How PrepareForInput impact the worker performance?  and what happens if the confg was misleading
*Okey, it has big performance impact on the first prediction (heavy freeze), i recommend every one to use it*

4) Execute freezes the game, i saw that you are using while(move.next) with the async, when i use it like this yield return movenext, it works fine, but otherwise it stuck

5) Is there a way to reuse tensor? i am working on a video processing , single prediction for frame
Thank you 👍

**Comment by AlexRibard** [comment]
Hey @DanielDorDev ! Thanks for the feedback, it is very appreciated :)

* Question 1:
Since you are dealing with images, I would suggest you stay on the GPU pipe.
You can create Tensors directly from Textures or RenderTextures.
```
var tensor = Tensor(srcTexture, numberofchannels);
```
Depending on your processing, I would generally suggest you do that directly in a ComputeShader, as it will give you the most flexibility.
(https://stackoverflow.com/questions/51727164/how-to-modify-a-texture-pixels-from-a-compute-shader-in-unity gives a good overview on how to do that)

* Question 2:
You have two options atm:
- use a different post process network that you build in Pytorch or with the model builder:
```
Model model = new Model();
var builder = new ModelBuilder(model);
builder.Sigmoid(...)
...
IWorker workerFused = WorkerFactory.CreateWorker(workerType, model);
```
- you can also use the model builder to append a layer to your base model:
```
var builder = new ModelBuilder(myModel);
builder.Sigmoid(...)
...
IWorker workerFused = WorkerFactory.CreateWorker(workerType, builder.model);
```
(remember to do that before creating the `Worker`)

* Question 3:
PrepareForInput pre-allocates model Tensor data as well as does some basic scheduling optimizations so we can de-alloc memory when not used. So it has a large overhead, but then you win when executing the network.
I would recommend calling once right after the worker and not every frame

* Question 4:
Indeed if you just call Execute we will dispatch the whole network to the GPU. If that takes more than a frame, the game freezes. To avoid this you can use `Scheduled Execution` to execute parts of your network every frame
https://github.com/Unity-Technologies/barracuda-release/blob/release/1.0.0/Documentation%7E/ModelExecution.md

* Question 5:
Once you created a Tensor, it stays in memory until you dispose it.
So in your case you can have a private Tensor and only dispose it when ending your application

Hope that helps

**Comment by DanielDorDev** [comment]
Thank you for the answer !

2) I tried adding layer, but because i have 4, it doesn't work, i don't want to sigmoid everything, only single output.

3) Yes i am using it only in the construction (because i use the same prediction bhwc , it doesn't change), so great to know, i think it is a good idea to mention in the documents :)

4) Is there a better way? yield return the scheduled execution take too much time(100 layers)
for example , yield reutrn moveNext : takes 2 seconds
moveNext, and then yield return moveNext : takese 1 second
but the in single frame it takes less then 0.25 seconds.
How can i deal with that? 
// It only appear in the editor, in build the problem disappear, and there is profiler.sample error, maybe it's connected?

5) Lets say i wrap worker with tensorWorker, it has private tensor , and the worker parameters, i want to update the old tensor with texture that been modified in compute shader, i change what? 
(i want to prevent the cpu reading from gpu to tensor),

**Comment by AlexRibard** [comment]
2. 
If you know the name of the output, you can simply do the following
```
builder.Sigmoid("output0Sigmoid","output0"); // output0 feeds now into a Sigmoid function - new output is called output0Sigmoid
```
4.
Are you able to repro it with a simple project so I can check it out?
5.
For internal reasons, when creating a Tensor from a Texture, you will need to re-create said Tensor if the Texture changes internally. But fear not, if you are using a Compute worker, everything stays on the GPU :) (even if you re-create the Tensor every frame)
So just do:
```
var input = new Tensor(myRenderTexture, 3);
...
```

**Comment by DanielDorDev** [comment]
Thanks again, i am learning a lot from your answers !  :)
2) I will try it out and update if it worked => **worked like a charm**

3) I will do this later and send the repro,  for now i am getting this error
```
Non matching Profiler.EndSample (BeginSample and EndSample count must match): 
Previous 5 samples:
	Mono.JIT
	GC.Alloc
	Barracuda.SizeAllocator.Alloc
	GC.Alloc
	Barracuda.Nop
In the scope:
	Assembly-CSharp.dll!ModelGameObject::ClassName.Classify() [Coroutine: MoveNext]
	CoroutinesDelayedCalls
	Update.ScriptRunDelayedDynamicFrameRate
	PlayerLoop
	Main Thread
```

5) Can you please explain , my goal is to minimize overhead:

(Live feed for webcamtexture is the target texture 📷 )

Until now, 

- readpixels(webcamtexture, color32[])
- setpixels(savedTexture)
- resize and value preprocessing
- new Tensor(savedTexture, 3)
- worker.Setinput(tensor)
-execute
-dispose
(TODO  compute shader after i learn how to use it ✌️ ).

So with compute shader

bilt with the shader (still on the gpu), 
new tensor(textureAfterShader, 3)
worker.setInput(tensor)
execute
dispose
 Is the correct way (=low overhead)
I though if it is possible only to change the computebuffer, so every time i use compute shader, i will post the result directly 


another little question , if i want to support both gpu and cpu, i need to create different articture  right? , one that use shader and precompiled worker

and the other will prefer array and job system(with burst)

**Comment by AlexRibard** [comment]
For webcam, you can follow this tutorial, it is similar to what you are trying to achieve
https://github.com/AlexRibard/Barracuda-U-2-NetTest
But in short
```
    void Update()
    {
       // webcam -> render texture (easy down-scaling with a material)
        var webcamRT = RenderTexture.GetTemporary(inputResolutionX, inputResolutionY, 0);
        Graphics.Blit(m_WebcamTexture, webcamRT, material);

        int kernelHandle = shader.FindKernel("CSMain");
        shader.SetTexture(kernelHandle, "Input", targetRT);
        shader.SetTexture(kernelHandle, "Result", postProcesedTexture);
        shader.Dispatch(kernelHandle, targetRT.width / 8, targetRT.height / 8, 1);

        Tensor input = new Tensor(postProcesedTexture, 3);
        worker.Execute(input);
    }
```
Compute Shader side
```
pragma kernel CSMain

Texture2D<float3> Input;
RWTexture2D<float3> Result;

[numthreads(8,8,1)]
void CSMain (uint3 id : SV_DispatchThreadID)
{
	float3 rgb = Input[id.xy];
....
	Result[id.xy] = rgb;
}
```

**Comment by AlexRibard** [comment]
For what I wrote, the worker will need to be on the GPU.
But the advantage is that you have very low overhead. Image processing is fast, Image to Tensor is fast (since on the same pipe)

If you want a CPU worker, you have two options:
*
Keep your current pipeline and change the worker to be CPU.
*
Keep the texture processing on the GPU for speed.
And download the RenderTexture into a regular texture2d and create the Tensor from that. And use a CPU worker.

**Comment by AlexRibard** [comment]
closing for now.
@DanielDorDev let me know if you have other questions
