### ISSUE TITLE
3D texture from tensor ?

### ISSUE THREAD

**Issue by albanmdb3d** [Unity-Technologies/barracuda-release#78]
Hi! 
I am fairly new to Unity and Barracuda. I have a model that requires a fair amount of post-processing. My model outputs a tensor of shape (1, 64, 64, 243) in BHWC format. In need to permute some dimensions but this is not yet supported by Barracuda, so I am trying to do it manually. My idea is to export my tensor to a texture and use a compute shader to do what I need. From my understanding, a Render Texture is kind of like a 2D array. Calling Tensor.TensorToRenderTexture with the default parameters fill export the first channel of my tensor correct? Is there a way to export the tensor with all the channels?

Thanks for the awesome work!

**Comment by AlexRibard** [comment]
Hi @albanmdb3d ! How do you need to permute dimensions exactly?
Depending on which version you are on, we have the `Tensor Transpose(Tensor X, int[] permutations)` operator.
It works as `numpy.transpose`
Ex: Transpose(X, [0,3,2,1]) => tensor of shape 1,243,64,64 in your case.

Alternatively you could transpose it directly on the CPU! In that case, just access the tensor with [] accessor directly.

If you want to go with a RenderTexture, I would recommend you use a 3D texture (which is a 3D array + rgba so 3x4D array)
https://docs.unity3d.com/ScriptReference/Texture3D.html
In that case it'll load HWC directly. So it seems more suited to your need.
With 2D textures, you'll need to load 4 channels at a time in one texture (since it is a 2D+rgba array, so 2x4D array).
So you'll need to handle 61 Textures... Which is not ideal.
To load the 3D texture, you can call `TensorToRenderTexture` with a 3D texture as argument and it will override the RenderTexture input.

So by order of ease of use:
* Transpose operator
* manually transpose on CPU
* use a 3D texture

**Comment by albanmdb3d** [comment]
Hi Alex.

Thanks' for the quick response. I am working with the latest version ie. 1.0.1. The Transpose operator looks like what I need. Initially, transpose was included in my ONNX model but this always caused errors upon import, hence my plan to do it manually. I can provide more details about the errors I get if needed.
I can't seem to find the Transpose declaration on the API page. Under the [IOps doc](https://docs.unity3d.com/Packages/com.unity.barracuda@0.7/api/Unity.Barracuda.IOps.html), all I find is `Tensor Transpose(Tensor x)`. I can't find anything under the Tensor page. 
In my script, when I call `int[] dimensions = new int[] {0,3,2,1}; Transpose(output, dimensions);`, I get the following error: There is no argument given that corresponds to the required formal parameter 'dim2' of 'ModelInference.Transpose(Tensor, int, int)'.

Thank you!

**Comment by AlexRibard** [comment]
ah! 
It would seem that we haven't done a major release that includes that change yet... Sorry about that.

How would like to proceed then?
I can send you the code to do it on CPU and you use that while you wait for the code to be released?
Or I give you the full code of the PR to get ONNX and GPU support, but it might be a bit long for you to paste it everywhere?

**Comment by albanmdb3d** [comment]
You're welcome! I'm glad this "bug" will be covered soon as it's giving me headaches at the moment :smiley: . 
When should the next released arrive? I think the full code would be nice because that would mean I will probably be able to export my entire model and not have to deal with permutations myself. Thanks' for the support!

**Comment by AlexRibard** [comment]
Should be released within a week or so. 
Do you have a personal email that I can forward you the PR?

**Comment by albanmdb3d** [comment]
Great looking forward to the next release. You can email at alban dot deboissiere dot gmail got com. Thanks' again for the assistance.

**Comment by albanmdb3d** [comment]
Hi @AlexRibard , did you have the opportunity to send me the PR ? I didn't receive anything so far. Thank you!

**Comment by AlexRibard** [comment]
hi sorry, things got busy on my end. I send you an email with the PR details

**Comment by albanmdb3d** [comment]
Hi, sorry for the delay. It looks like I haven't received anything. Perhaps you miswrote the email?

**Comment by AlexRibard** [comment]
I send it to deboissiere@gmail.com.
You can contact me directly at barracuda-support@unity3d.com if you wish, it'll be simpler

**Comment by albanmdb3d** [comment]
You forgot my first name :) . I sent you an email instead. I'm closing the issue.

**Comment by AlexRibard** [comment]
oups! my bad. Yeah send me an email then
