### ISSUE TITLE
NonZero operator request + GPU to CPU takes a really long time

### ISSUE THREAD

**Issue by albanmdb3d** [Unity-Technologies/barracuda-release#83]
Hello (it's me again).

I would like to index a tensor with boolean values. The equivalent Python code is something like this:

```python
idxs = tensor > 0.5
new_tensor = tensor[idxs]
```

In ONNX this would be a combination of NonZero + Gather or using where. Gather is already available so no biggy, I'll just filter my values on the CPU and use the Gather op. But getting a GPU value to CPU takes abnormally long (~1.5s).  

Here is what I do:
```c#
Tensor positivesIdx = mOps.Greater(maxClassConfidence, threshold);  // shape (16368, 1, 1, 1)
float[] data = positivesIdx.data.Download(positivesIdx.shape);
```

`positivesIdx` is of shape (16000, 1) so it's not even that big. 

Do you intend to implement the NonZero/Where ops in the near future? How come GPU to CPU takes so long ?

Thanks'!

**Comment by AlexRibard** [comment]
I am currently working on `Where` so that should come soon. NonZero shouldn't take long either.

I'll refer you to this to download the data from GPU/CPU.
https://github.com/Unity-Technologies/barracuda-release/blob/release/1.0.0/Documentation%7E/ModelOutput.md
Did you try accessing your tensor with default accessors `[]` directly, we should handle the download.
Or if you want the array, the recommended way to do it is `ToReadOnlyArray`
The issue might be that you might run into a synch between the GPU/CPU. But hard to tell without knowing what your frame is made up of.

**Comment by mantasp** [comment]
> But getting a GPU value to CPU takes abnormally long (~1.5s).

Typically this means that GPU hasn't yet finished computing your model. So you most likely will see same performance issue even after these ops are added to the Barracuda. Any chance you could provide more details on what kind of model are you running and what kind of input are you passing to the network? It would help us identify if such long execution time is expected or not.

**Comment by albanmdb3d** [comment]
I believe the issue is indeed a synch between GPU/CPU. The GPU to CPU op comes after my model has finished computing as part of the post-processing. I am working on implementing NonZero on the GPU I'll let you know if that fixes the bottleneck. 
Thanks' for the feedback

**Comment by albanmdb3d** [comment]
I implemented a rough NonZero ReferenceCompute op on the GPU and it fixed the lag spike. That will do for now. I'm very much looking forward to your implementation of Where & NonZero as I'm curious about how you deal with a dynamic output size in a compute shader. I'm closing the issue, thanks' again for the support :smile:

**Comment by AlexRibard** [comment]
I have pushed `Where` on latest. Should come out in next release
